name: pixl
description: Music is for all

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  nes_ui: ^0.24.1
  animated_splash_screen: ^1.3.0
  flutter_bloc: ^9.1.1
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/
    - assets/images/pixl_animation.gif
    - assets/images/pixl.png

  uses-material-design: true
